version: 2
jobs:
  build:
    docker:
      - image: erulabs/circleci-builder:11
    working_directory: ~/repo
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: false
          version: 17.06.1-ce

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Installing
          command: yarn --no-progress --no-emoji --prefer-offline

      - run:
          name: Linting
          command: ./bin/lint.sh

      - run:
          name: Testing
          command: ./bin/test.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
