apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "{{name}}"
    env: "{{env}}"
    deployedBy: deploy-node-app
  name: "{{name}}-{{env}}"
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "{{name}}"
      env: "{{env}}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{name}}"
        env: "{{env}}"
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: "{{image}}"
          imagePullPolicy: Always
          name: "{{name}}"
          command: "{{command}}"
          ports:
            - containerPort: "{{port}}"
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 32Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
